server:
  port: 8085

spring:
  application:
    name: service-exchange
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/simple-bank/protocol/openid-connect/certs
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/exchange-db
    username: postgres
    password: postgres

headers:
  user-header: X-User-Login

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    web: info
    org.springframework.security: info

services:
  service-gateway:
    name: "simple-bank-service-gateway:8080"