server:
  port: 8085

spring:
  application:
    name: bank-exchange-generator
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/simple-bank/protocol/openid-connect/certs
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/exchange-db
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 0
      retries: 0

kafka-topics:
  exchange-rates-topic: topic-bankapp-exchange-rates

headers:
  user-header: X-User-Login

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    web: info
    org.springframework.security: info

services:
  bank-gateway:
    name: "simple-bank-bank-gateway:8080"