server:
  port: 8086
spring:
  application:
    name: bank-cash

  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: bank-front-route
              uri: http://simple-bank-bank-gateway:8080
              predicates:
                - Path=/
              filters:
                - TokenRelay=simple-bank-client

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8180/realms/simple-bank/protocol/openid-connect/token
            authorization-uri: http://localhost:8180/realms/simple-bank/protocol/openid-connect/auth
            jwk-set-uri: http://localhost:8180/realms/simple-bank/protocol/openid-connect/certs
        registration:
          simple-bank-client:
            client-id: simple-bank-client
            client-secret: VmGXQDXNGOZzJH5Mx7Fi4OyHtnb3IH8A
            authorization-grant-type: client_credentials
            scope: openid
            provider: keycloak

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all

kafka-topics:
  notifications-topic: topic-bankapp-notifications

resilience4j:
  retry:
    instances:
      gateway-service:
        max-attempts: 3
        wait-duration: 1s
  circuitbreaker:
    instances:
      gateway-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

headers:
  user-header: X-User-Login

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    web: info
    org.springframework.security: info

services:
  bank-gateway:
    name: "simple-bank-bank-gateway:8080"