apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bank-notifications.fullname" . }}-config
  labels:
    {{- include "bank-notifications.labels" . | nindent 4 }}
data:
  # OAuth2 Configuration
  oauth2-resource-server-jwk-set-uri: "http://simple-bank-keycloak:8080/realms/simple-bank/protocol/openid-connect/certs"
  
  # Database Configuration
  r2dbc-url: "r2dbc:postgresql://simple-bank-postgresql-notifications:5432/notifications-db"
  r2dbc-username: "postgres"

  # Kafka Configuration
  kafka-brokers: "bankapp-kafka:9092"
  kafka-topics.notifications-topic: "topic-bankapp-notifications"

  zipkin-tracing-endpoint: "http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans"