apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bank-exchange-generator.fullname" . }}-config
  labels:
    {{- include "bank-exchange-generator.labels" . | nindent 4 }}
data:
  # OAuth2 Configuration
  oauth2-resource-server-jwk-set-uri: "http://simple-bank-keycloak:8080/realms/simple-bank/protocol/openid-connect/certs"
  
  # Database Configuration
  r2dbc-url: "r2dbc:postgresql://simple-bank-postgresql-exchange:5432/exchange-db"
  r2dbc-username: "postgres"

  # Kafka Configuration
  kafka-brokers: "bankapp-kafka:9092"