server:
  port: 8083

spring:
  application:
    name: bank-blocker
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/simple-bank/protocol/openid-connect/certs

headers:
  user-header: X-User-Login

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    web: info
    org.springframework.security: info

services:
  bank-gateway:
    name: "simple-bank-bank-gateway:8080"