server:
  port: 8081

spring:
  application:
    name: service-convert

  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: service-front-route
              uri: http://simple-bank-service-gateway:8080
              predicates:
                - Path=/
              filters:
                - TokenRelay=simple-bank-client
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8180/realms/simple-bank/protocol/openid-connect/token
            authorization-uri: http://localhost:8180/realms/simple-bank/protocol/openid-connect/auth
            jwk-set-uri: http://localhost:8180/realms/simple-bank/protocol/openid-connect/certs
        registration:
          simple-bank-client:
            client-id: simple-bank-client
            client-secret: VmGXQDXNGOZzJH5Mx7Fi4OyHtnb3IH8A
            authorization-grant-type: client_credentials
            scope: openid
            provider: keycloak
resilience4j:
  retry:
    instances:
      gateway-service:
        max-attempts: 3
        wait-duration: 1s
  circuitbreaker:
    instances:
      gateway-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

headers:
  user-header: X-User-Login

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    web: info
    org.springframework.security: info


services:
  service-gateway:
    name: "simple-bank-service-gateway:8080"