server:
  port: ${services.bank-notifications.port}

spring:
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: localhost:2181

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/simple-bank/protocol/openid-connect/certs

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: true

  r2dbc:
    url: r2dbc:postgresql://localhost:5434/notifications-db
    username: postgres
    password: postgres