server:
  port: ${services.gateway-server.port}

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: localhost:2181

    gateway:
      server:
        webflux:
          routes:
            - id: front-route
              uri: lb://bank-front
              predicates:
                - Path=/
              filters:
                - TokenRelay=simple-bank-client
                - UserHeader

            - id: front-main-route
              uri: lb://bank-front
              predicates:
                - Path=/main
              filters:
                - TokenRelay=simple-bank-client
                - UserHeader

            - id: accounts-post-signup-route
              uri: lb://bank-accounts
              predicates:
                - Path=/api/signup
                - Method=POST
              filters:
                - TokenRelay=simple-bank-client

            - id: edit-password-route
              uri: lb://bank-accounts
              predicates:
                - Path=/user/{login}/editPassword
              filters:
                - TokenRelay=simple-bank-client

            - id: exchange-route
              uri: lb://bank-exchange-generator
              predicates:
                - Path=/api/rates
              filters:
                - TokenRelay=simple-bank-client

            - id: edit-accounts-route
              uri: lb://bank-accounts
              predicates:
                - Path=/user/{login}/editUserAccounts
              filters:
                - TokenRelay=simple-bank-client

            - id: cash-route
              uri: lb://bank-cash
              predicates:
                - Path=/user/{login}/cash
              filters:
                - TokenRelay=simple-bank-client

            - id: notifications-route
              uri: lb://bank-notifications
              predicates:
                - Path=/api/{login}/notifications
              filters:
                - TokenRelay=simple-bank-client

            - id: transfer-route
              uri: lb://bank-transfer
              predicates:
                - Path=/user/{login}/transfer
              filters:
                - TokenRelay=simple-bank-client

            - id: blocker-route
              uri: lb://bank-blocker
              predicates:
                - Path=/api/block/{value}
              filters:
                - TokenRelay=simple-bank-client

            - id: cash-balance-route
              uri: lb://bank-accounts
              predicates:
                - Path=/api/{login}/cash
              filters:
                - TokenRelay=simple-bank-client

            - id: get-account-route
              uri: lb://bank-accounts
              predicates:
                - Path=/api/{login}/account/{currency}
              filters:
                - TokenRelay=simple-bank-client

            - id: convert-route
              uri: lb://bank-exchange
              predicates:
                - Path=/api/convert
              filters:
                - TokenRelay=simple-bank-client

            - id: accounts-user-route
              uri: lb://bank-accounts
              predicates:
                - Path=/api/{login}/user
              filters:
                - TokenRelay=simple-bank-client

            - id: accounts-user-accounts-route
              uri: lb://bank-accounts
              predicates:
                - Path=/api/{login}/accounts
              filters:
                - TokenRelay=simple-bank-client

            - id: accounts-users-route
              uri: lb://bank-accounts
              predicates:
                - Path=/api/users
              filters:
                - TokenRelay=simple-bank-client

            - id: accounts-currencies-route
              uri: lb://bank-accounts
              predicates:
                - Path=/api/currencies
              filters:
                - TokenRelay=simple-bank-client

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8180/realms/simple-bank/protocol/openid-connect/token
            authorization-uri: http://localhost:8180/realms/simple-bank/protocol/openid-connect/auth
            jwk-set-uri: http://localhost:8180/realms/simple-bank/protocol/openid-connect/certs
        registration:
          simple-bank-client:
            client-id: simple-bank-client
            client-secret: VmGXQDXNGOZzJH5Mx7Fi4OyHtnb3IH8A
            authorization-grant-type: client_credentials
            scope: openid
            provider: keycloak

  thymeleaf:
    encoding: UTF-8
    mode: HTML

resilience4j:
  retry:
    instances:
      gateway-service:
        max-attempts: 3
        wait-duration: 1s
  circuitbreaker:
    instances:
      gateway-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s