apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bank-blocker.fullname" . }}-config
  labels:
    {{- include "bank-blocker.labels" . | nindent 4 }}
data:
  # OAuth2 Configuration (minimal for blocker service)
  oauth2-resource-server-jwk-set-uri: "http://simple-bank-keycloak:8080/realms/simple-bank/protocol/openid-connect/certs"